# Generated by Django 5.2.6 on 2025-09-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepaiapp', '0004_alter_course_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcourse',
            name='generated_course',
        ),
        migrations.RemoveField(
            model_name='customcourse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learningsession',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='learningsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usercourseenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercourseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourseenrollment',
            name='last_accessed_subtopic',
        ),
        migrations.RemoveField(
            model_name='usercourseenrollment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usersubtopicprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersubtopicprogress',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='usersubtopicprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='prerequisites',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='CustomCourse',
        ),
        migrations.DeleteModel(
            name='LearningSession',
        ),
        migrations.DeleteModel(
            name='UserCourseEnrollment',
        ),
        migrations.DeleteModel(
            name='UserSubtopicProgress',
        ),
    ]
